// ============================================================
// Custom OpenTelemetry metrics for CSAT.
// ------------------------------------------------------------
// HTTP / process / DB metrics come free from auto-instrumentation
// + host-metrics. This file defines the BUSINESS / OPS metrics
// that aren't autogenerated:
//
//   - cron.backup.last_success_timestamp (observable gauge)
//       Drives the CronBackupMissed alert in vmalert/rules/backend.yaml.
//       Kept as a module-scope timestamp so the gauge callback stays cheap.
//
// Add new metrics here so all custom instrument definitions live in
// one place — easy to audit cardinality and naming.
// ============================================================

import { metrics } from '@opentelemetry/api';

const meter = metrics.getMeter('csat-server');

// Internal state — module-scoped because gauges read it on every export tick.
let lastBackupSuccessTimestamp = 0;

// Observable gauge: emits the unix timestamp of the last successful cron
// backup. 0 means "never ran since process start" — alert rule excludes
// that case so a fresh deploy doesn't immediately page.
meter
  .createObservableGauge('cron.backup.last_success_timestamp', {
    description: 'Unix timestamp (seconds) of the last successful monthly backup. 0 = never.',
    unit: 's',
  })
  .addCallback(observable => {
    observable.observe(lastBackupSuccessTimestamp);
  });

// Counter: total backup attempts (success + failure) per outcome.
const backupAttemptsCounter = meter.createCounter('cron.backup.attempts', {
  description: 'Number of monthly backup attempts.',
});

// Histogram: backup duration. Useful for trend dashboards (Phase 4+).
const backupDurationHistogram = meter.createHistogram('cron.backup.duration', {
  description: 'Wall-clock duration of monthly backup runs.',
  unit: 's',
});

/**
 * Record a successful backup. Called from src/config/cron.js after
 * createBackup() resolves without throwing.
 *
 * @param {number} durationSeconds  How long the backup took.
 */
export const recordBackupSuccess = (durationSeconds) => {
  lastBackupSuccessTimestamp = Math.floor(Date.now() / 1000);
  backupAttemptsCounter.add(1, { outcome: 'success' });
  if (typeof durationSeconds === 'number') {
    backupDurationHistogram.record(durationSeconds, { outcome: 'success' });
  }
};

/**
 * Record a failed backup. Doesn't update the last-success timestamp.
 * Called from src/config/cron.js when createBackup() rejects.
 */
export const recordBackupFailure = (durationSeconds) => {
  backupAttemptsCounter.add(1, { outcome: 'failure' });
  if (typeof durationSeconds === 'number') {
    backupDurationHistogram.record(durationSeconds, { outcome: 'failure' });
  }
};
